### ISSUE TITLE
Request: track bytes for other scalar objects

### ISSUE THREAD

**Issue by rdominy** [jhuckaby/pixl-cache#1]
Currently the cache only track bytes if the object being stored has a length property.  It would be helpful if tracked other values such as integer, float, booleans.  For one of my projects I use the NPM module sizeof to get the byte count of an object.

**Comment by jhuckaby** [comment]
Thanks!  I would be happy to implement this.  However, currently pixl-cache has zero dependencies, and I've love to keep it that way, so I think I'll just "borrow" some code from `sizeof` to calculate the JS primitive byte counts.

**Comment by jhuckaby** [comment]
Fixed in v1.0.6.  Thanks!
