### ISSUE TITLE
Bytes used should also track key size

### ISSUE THREAD

**Issue by rdominy** [jhuckaby/pixl-cache#2]
When tracking bytes consumed, the module should also track the size of the keys as those may represent a substantial part of the storage.

**Comment by jhuckaby** [comment]
Haha, I was just implementing this as part of the changes for issue #1 when this notification came in.  Going in right away!

**Comment by rdominy** [comment]
👍 I was a little surprised after testing my class to persist the cache to S3 with 100K items the total byte count was 9 :)

**Comment by jhuckaby** [comment]
Haha oops 😆

**Comment by jhuckaby** [comment]
Fixed in v1.0.6.  Thanks!
